[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_rust = "6i8YpAr8uQEZax7SGFPc6X7zqqdD63gw9gxn2X6xWHwW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/shoya-sue/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
